#!/usr/bin/env python3

import json
import re
import sys
from distutils.version import StrictVersion
from ftplib import FTP
from urllib.parse import urlparse

params = json.loads(sys.stdin.read())

uri = urlparse(params['source']['uri'])
regex = re.compile(params['source']['regex'])

with FTP() as ftp:
    # connect and login
    ftp.connect(uri.hostname, uri.port)
    if uri.username:
        ftp.login(uri.username, uri.password)
    else:
        ftp.login()

    # get list of files from desired location
    ftp.cwd(uri.path)

    versions = []

    def add_to_versions(line):
        """Add version to list of version if matches regex."""
        match = regex.search(line)
        if match:
            versions.append(match.groups()[0])

    file_lines = ftp.retrlines('LIST', add_to_versions)

    versions.sort(key=StrictVersion)
    output = [{"ref": v} for v in versions]

    print(json.dumps(output))
