#!/usr/bin/env python3

import json
import logging
import re
import sys
from distutils.version import StrictVersion
from ftplib import FTP
from urllib.parse import urlparse

params = json.loads(sys.stdin.read())

if params['source'].get('debug', True):
    logging.basicConfig(level=logging.DEBUG)

logging.debug('params: %s', params)

uri = urlparse(params['source']['uri'])
regex = re.compile(params['source']['regex'])
version_key = params['source'].get('version_key', 'version')

with FTP() as ftp:
    # connect and login
    ftp.connect(uri.hostname, uri.port)
    if uri.username:
        ftp.login(uri.username, uri.password)
    else:
        ftp.login()

    # get list of files from desired location
    ftp.cwd(uri.path)

    versions = []

    def add_to_versions(line):
        """Add version to list of version if matches regex."""
        logging.debug('ftp file line %s', line)
        match = regex.search(line)
        if match:
            versions.append(match.groupdict())

    file_lines = ftp.retrlines('LIST', add_to_versions)

    versions.sort(key=lambda x: StrictVersion(x[version_key]))
    output = [
        {
            'version': {version_key: v[version_key]},
            'metadata': [{"name": k, "value": v} for k, v in v.items() if not k == version_key]
            } for v in versions]

    print(json.dumps(output))
