#!/usr/bin/env python

import json
import logging
import re
import sys
from urlparse import urlparse

import ftputil
from common import UriSession, matching_versions, versions_to_output

params = json.loads(sys.stdin.read())

if params['source'].get('debug', True):
    logging.basicConfig(level=logging.DEBUG)

logging.debug('params: %s', params)

uri = urlparse(params['source']['uri'])
regex = re.compile(params['source']['regex'])
version_key = params['source'].get('version_key', 'version')

with ftputil.FTPHost(uri, session_factory=UriSession) as ftp:
    # get matching version from file list
    versions = matching_versions(ftp.listdir('.'), regex)

output = versions_to_output(versions, version_key)

print(json.dumps(output))
