#!/usr/bin/env python3

import json
import logging
import os
import sys
from ftplib import FTP
from urllib.parse import urlparse

params = json.loads(sys.stdin.read())

if params['source'].get('debug', True):
    logging.basicConfig(level=logging.DEBUG)

dest_dir = sys.argv[1]

logging.debug('params: %s', params)
logging.debug('dest_dir: %s', dest_dir)

uri = urlparse(params['source']['uri'])
template = params['source'].get('template', '')
version_key = params['source'].get('version_key', 'version')
version = params['version']['version']

if template:
    file_name = template.format(version=version)
else:
    file_name = version

dest_file_path = os.path.join(dest_dir, file_name)

with FTP() as ftp:
    # connect and login
    ftp.connect(uri.hostname, uri.port)
    if uri.username:
        ftp.login(uri.username, uri.password)
    else:
        ftp.login()

    ftp.cwd(uri.path)

    with open(dest_file_path, 'wb') as f:
        ftp.retrbinary('RETR {}'.format(file_name), f.write)

version = {
    version_key: version,
    "file": file_name,
}

output = {'version': {version_key: version[version_key]}}
if len(version.keys()) > 1:
    output.update({'metadata': [
        {"name": k, "value": v} for k, v in version.items() if not k == version_key
    ]})

print(json.dumps(output))
