#!/usr/bin/env python3

import json
import os
import sys
from ftplib import FTP
from urllib.parse import urlparse

params = json.loads(sys.stdin.read())

uri = urlparse(params['source']['uri'])
template = params['source']['template']
dest_dir = sys.argv[1]
version = params['version']['ref']

file_name = template.format(version=version)

dest_file_path = os.path.join(dest_dir, file_name)

with FTP() as ftp:
    # connect and login
    ftp.connect(uri.hostname, uri.port)
    if uri.username:
        ftp.login(uri.username, uri.password)
    else:
        ftp.login()

    ftp.cwd(uri.path)

    with open(dest_file_path, 'wb') as f:
        ftp.retrbinary('RETR {}'.format(file_name), f.write)

    print(json.dumps({'version': {'ref': version}}))
