#!/usr/bin/env python

import json
import logging
import os
import re
import sys
from urlparse import urlparse

import ftputil
from common import UriSession, matching_versions, version_to_output

params = json.loads(sys.stdin.read())

if params['source'].get('debug', True):
    logging.basicConfig(level=logging.DEBUG)

dest_dir = sys.argv[1]

logging.debug('params: %s', params)
logging.debug('dest_dir: %s', dest_dir)

uri = urlparse(params['source']['uri'])
regex = re.compile(params['source']['regex'])
version_key = params['source'].get('version_key', 'version')
version = params['version']['version']

with ftputil.FTPHost(uri, session_factory=UriSession) as ftp:
    # get matching version from file list
    versions = matching_versions(ftp.listdir('.'), regex)

    match_version = next(v for v in versions if v[version_key] == version)

    file_name = match_version['file']
    dest_file_path = os.path.join(dest_dir, file_name)

    ftp.download(file_name, dest_file_path)

output = version_to_output(match_version, version_key)

print(json.dumps(output))
