#!/usr/bin/env python3

import glob
import json
import logging
import os
import sys
from ftplib import FTP
from urllib.parse import urlparse

logging.basicConfig(level=logging.DEBUG)

params = json.loads(sys.stdin.read())
src_dir = sys.argv[1]

logging.debug('params: %s', params)
logging.debug('src_dir: %s', src_dir)

uri = urlparse(params['source']['uri'])
file_glob = params['params']['file']

src_file_path = glob.glob(os.path.join(src_dir, file_glob))[0]
file_name = src_file_path.split('/')[-1]

with FTP() as ftp:
    # connect and login
    port = uri.port or 21
    ftp.connect(uri.hostname, port)
    if uri.username:
        ftp.login(uri.username, uri.password)
    else:
        ftp.login()

    ftp.cwd(uri.path)

    with open(src_file_path, 'rb') as f:
        ftp.storbinary('STOR {}'.format(file_name), f)

    print(json.dumps({'version': {'ref': file_name}}))
